type token = OPEN_VALIDITY
           | CLOSE_VALIDITY
           | OPEN_DISJUNCTION
           | CLOSE_DISJUNCTION
           | OPEN_CONJUNCTION
           | CLOSE_CONJUNCTION
           | TRUE
           | FALSE
           | OPEN_NOT
           | CLOSE_NOT
           | OPEN_ATOM
           | CLOSE_ATOM
           | OPEN_LESS
           | CLOSE_LESS
           | OPEN_LESS_EQ
           | CLOSE_LESS_EQ
           | OPEN_EQ
           | CLOSE_EQ
           | OPEN_SUM
           | CLOSE_SUM
           | OPEN_PRODUCT
           | CLOSE_PRODUCT
           | OPEN_NUM
           | CLOSE_NUM
           | OPEN_VAR
           | CLOSE_VAR
           | OPEN_PAR
           | CLOSE_PAR
           | ASSERT
           | AND
           | OR
           | NOT
           | LET
           | EQ
           | LT
           | GT
           | LEQ
           | GEQ
           | PLUS
           | MINUS
           | TIMES
           | DIVIDED
           | NUM 
           | VAR
           | EOF;;